- name: NETCONF Test - JunOS
  hosts: slc2-int-switches-junos
  roles:
  - Juniper.junos
  connection: local
  gather_facts: no

  tasks:

  - name: Checking NETCONF connectivity
    wait_for: host={{ inventory_hostname }} port=830 timeout=5

