- name: Push Firmware To Devices
  connection: local
  hosts: asa-all
  gather_facts: false

  tasks:
  - name: SCP Firmware Onto Device
    local_action: command scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no /tftpboot/asa/{{ firmware_image }} databank@{{ inventory_hostname }}:disk0:{{ firmware_image }}

