- name: SSH Test - ASA
  hosts: asa-test
  serial: 1
  connection: local
  gather_facts: no

  tasks:

  - name: Checking SSH connectivity
    wait_for: host={{ inventory_hostname }} port=22 timeout=30

