---
- name: Checking NETCONF connectivity
  wait_for: host={{ inventory_hostname }} port=830 timeout=5

- name: Install JunOS Software
  junos_install_os:
   user=databank
   host={{ inventory_hostname }}
   nssu=yes
   version={{ OS_version }}
   reboot=yes
   package={{ pkg_dir }}/{{ OS_package }}
   logfile={{ log_dir }}/software.log
  register: sw
  notify:
  - wait_reboot
  - send mail
