---
- name: Create a named maintenance window for host  for 90 minutes
  zabbix_maintenance:
    name: Update of "{{ inventory_hostname }}"
    host_name: "{{ inventory_hostname }}"
    state: present
    minutes: 90
    server_url: http://mci2-zabbix-master.databank.local/zabbix/
    login_user: zgould
    login_password: '@R3birth!!'

