---
- name: Checking NETCONF connectivity
  wait_for: host={{ inventory_hostname }} port=830 timeout=5

- name: Install JunOS Software
  junos_install_os:
   user=databank
   host={{ inventory_hostname }}
   nssu={{ nssu }}
   version={{ OS_version }}
   reboot=no
   package={{ pkg_dir }}/{{ OS_package }}
   logfile={{ log_dir }}/software.log

- name: Reboot JunOS
  junos_shutdown:
   user=databank
   host={{ inventory_hostname }}
   shutdown="shutdown"
   reboot=yes
  ignore_errors: yes

- name: Wait for Upgrade to Complete
  pause: 
   minutes: 30
   prompt: Waiting for Upgrade to Complete

- name: Validate Successful Upgrade
  junos_command:
   commands:
   - show version
   provider:
    username: databank
   wait_for: result[0] contains "{{ OS_version }}"
  register: validate_results
  ignore_errors: yes

- name: send mail - Success
  mail:
   subject: Firmware Upgrade of {{ inventory_hostname }} Complete
   body: ' Automated upgrade of {{ inventory_hostname }} is complete.
   Firmware has been upgraded to: {{ OS_version }}'
   to: zgould@databank.com
   cc: net-services@databank.com
   charset: utf8
  when: validate_results|succeeded

- name: send mail - Failure
  mail:
   subject: Firmware Upgrade of {{ inventory_hostname }} Failed.
   body: ' Automated upgrade of {{ inventory_hostname }} Failed.
   Please contact the Zack Gould (816-803-2029)'
   to: zgould@databank.com
   cc: net-services@databank.com
   charset: utf8
  when: validate_results|failed

